# Generated by Django 5.0.1 on 2024-01-28 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated_time',
        ),
    ]
