# Generated by Django 5.0.1 on 2024-01-25 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_cart_table_alter_product_table'),
        ('users', '0002_alter_user_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='buyer_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
    ]
