# Generated by Django 5.0.1 on 2024-01-26 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_capacity_cart_count_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='count_item',
            new_name='quantity',
        ),
    ]
