# Generated by Django 5.0.1 on 2024-01-26 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_count_item_cart_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='user_id',
            new_name='user',
        ),
    ]
