# Generated by Django 5.0.1 on 2024-01-26 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_item_id_cart_item_rename_user_id_cart_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productname',
            new_name='product_name',
        ),
    ]
