# Generated by Django 5.0.1 on 2024-01-26 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_rename_productname_product_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='productname',
        ),
    ]
