# Generated by Django 5.0.1 on 2024-01-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_cart_is_active_cart_is_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='is_ordered',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
